# Generated by Django 3.0.2 on 2020-01-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttime',
            name='time_end',
        ),
        migrations.AddField(
            model_name='posttime',
            name='time_keep_hour',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
            preserve_default=False,
        ),
    ]
