# Generated by Django 3.0.2 on 2020-01-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200127_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_posts',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to='trips.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modified_posts', to='trips.User'),
            preserve_default=False,
        ),
    ]
