# Generated by Django 3.0.2 on 2020-01-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20200127_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='trips.PostLocationTimeShip', verbose_name='活動時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='schedule_at',
            field=models.DateField(verbose_name='活動日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CB', '社團'), ('GUEST', '球友')], default='CB', max_length=5, verbose_name='身份'),
        ),
    ]
